import Foundation

@main
struct ApplicationTests {
    static func main() throws {
        let fm = FileManager.default
        let home = fm.temporaryDirectory.appendingPathComponent("AppTests-\(UUID().uuidString)").standardizedFileURL
        try fm.createDirectory(at: home, withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: home) }
        func write(_ relative: String, _ data: Data = Data("fixture".utf8)) throws -> URL {
            let url = home.appendingPathComponent(relative)
            try fm.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try data.write(to: url)
            return url
        }
        let info: [String: String] = ["CFBundleIdentifier": "org.macsweep.fixture", "CFBundleName": "FixtureApp", "CFBundleVersion": "1"]
        _ = try write("Applications/FixtureApp.app/Contents/Info.plist", PropertyListSerialization.data(fromPropertyList: info, format: .xml, options: 0))
        let catalog = AppCatalog(home: home)
        let app = catalog.readApp(home.appendingPathComponent("Applications/FixtureApp.app"))!
        let prefs = try write("Library/Preferences/org.macsweep.fixture.plist")
        let document = try write("Library/Application Support/org.macsweep.fixture/document.txt")
        _ = try write("Library/Application Support/FixtureApp/shared.txt")
        _ = try write("Library/Application Support/org.macsweep.fixture.other/do-not-touch.txt")
        _ = try write("Documents/my-work.txt")
        let plan = catalog.plan(app, installed: [app])
        precondition(plan.files.contains { $0.id == prefs.path && !$0.review })
        precondition(plan.files.contains { $0.id == document.deletingLastPathComponent().path && !$0.review })
        print("PASS: Exact app identifier matches preferences and private documents")
        precondition(plan.files.contains { $0.url.lastPathComponent == "FixtureApp" && $0.review })
        print("PASS: Name-only matches require manual review")
        precondition(!plan.files.contains { $0.id.contains("fixture.other") || $0.id.contains("/Documents/") })
        print("PASS: Similar identifiers and personal Documents excluded")
        let duplicate = InstalledApp(url: home.appendingPathComponent("Other.app"), name: app.name, bundleID: app.bundleID, version: "1", protected: false)
        precondition(catalog.plan(app, installed: [app, duplicate]).files.count == 1)
        print("PASS: Duplicate installation preserves associated data")
        precondition(plan.files.first { $0.id == prefs.path }?.group == .settings)
        precondition(plan.files.first { $0.id == document.deletingLastPathComponent().path }?.group == .documents)
        precondition(plan.files.first { $0.review }?.group == .review)
        print("PASS: Uninstall groups distinguish settings, documents and uncertain ownership")
        let sharedInfo = ["CFBundleIdentifier": "net.other.fixture", "CFBundleName": "FixtureApp", "CFBundleVersion": "1"]
        let sharedURL = home.appendingPathComponent("Applications/Shared.app")
        _ = try write("Applications/Shared.app/Contents/Info.plist", PropertyListSerialization.data(fromPropertyList: sharedInfo, format: .xml, options: 0))
        let sharedApp = catalog.readApp(sharedURL)!
        let sharedPath = home.appendingPathComponent("Library/Application Support/FixtureApp").path
        precondition(!catalog.plan(app, installed: [app, sharedApp]).files.contains { $0.id == sharedPath })
        print("PASS: Different App identifiers sharing a name cannot offer shared data")
        let lateShared = catalog.uninstall(plan, selected: Set(plan.files.map(\.id)))
        precondition(lateShared.0.isEmpty && lateShared.1.contains { $0.contains("重疊") } && fm.fileExists(atPath: document.path) && fm.fileExists(atPath: app.id))
        print("PASS: Newly installed shared owner blocks uninstall before any move")
        try fm.removeItem(at: sharedURL)
        let googleParent = InstalledApp(url: home.appendingPathComponent("Google.app"), name: "Google", bundleID: "net.fixture.google", version: "1", protected: false)
        let chromeOwner = InstalledApp(url: home.appendingPathComponent("Chrome.app"), name: "Chrome", bundleID: "com.google.Chrome", version: "1", protected: false)
        precondition(catalog.sharedRelatedPaths(chromeOwner, installed: [chromeOwner, googleParent]).contains(home.appendingPathComponent("Library/Application Support/Google/Chrome").path))
        precondition(catalog.sharedRelatedPaths(googleParent, installed: [chromeOwner, googleParent]).contains(home.appendingPathComponent("Library/Application Support/Google").path))
        print("PASS: Parent and child ownership overlaps are protected in both directions")
        var incomplete = plan
        incomplete.files.removeAll { $0.id == app.id }
        let missingBundle = catalog.uninstall(incomplete, selected: [app.id, prefs.path])
        precondition(missingBundle.0.isEmpty && !missingBundle.1.isEmpty && fm.fileExists(atPath: prefs.path))
        print("PASS: Missing bundle snapshot blocks associated data deletion")
        let unknownSelection = catalog.uninstall(plan, selected: [app.id, home.appendingPathComponent("unknown").path])
        precondition(unknownSelection.0.isEmpty && !unknownSelection.1.isEmpty && fm.fileExists(atPath: app.id))
        print("PASS: Stale selection is rejected instead of silently partially executing")
        _ = try write("Applications/Second.app/Contents/Info.plist", PropertyListSerialization.data(fromPropertyList: info, format: .xml, options: 0))
        let (lateRemoved, lateErrors) = catalog.uninstall(plan, selected: Set(plan.files.map(\.id)))
        precondition(lateRemoved.isEmpty && lateErrors.contains { $0.contains("另一份") })
        precondition(fm.fileExists(atPath: app.id) && fm.fileExists(atPath: prefs.path) && fm.fileExists(atPath: document.path))
        print("PASS: Installation added after inspection blocks all moves and preserves documents")
        let protected = InstalledApp(url: app.url, name: app.name, bundleID: app.bundleID, version: "1", protected: true)
        precondition(catalog.plan(protected, installed: []).files.isEmpty)
        print("PASS: Protected apps cannot be uninstalled")
        try fm.removeItem(at: prefs)
        try fm.createSymbolicLink(at: prefs, withDestinationURL: document)
        precondition(!catalog.plan(app, installed: [app]).files.contains { $0.id == prefs.path })
        print("PASS: Symlink preferences excluded")
        let (removed, errors) = catalog.uninstall(plan, selected: [])
        precondition(removed.isEmpty && !errors.isEmpty && fm.fileExists(atPath: app.url.path))
        print("PASS: Missing bundle selection rejected without modifying data")
        let orphan = try write("Library/Preferences/org.retired.example.plist")
        _ = try write("Library/Caches/org.macsweep.fixture.helper/data")
        _ = try write("Library/Preferences/com.apple.example.plist")
        _ = try write("Library/Caches/com.google.drivefs/data")
        _ = try write("Library/Application Support/org.retired.example/document")
        _ = try write("Library/Preferences/systemgroup.com.apple.example.plist")
        _ = try write("Library/Preferences/org.macsweep.shared.plist")
        let (leftovers, _) = catalog.leftovers()
        precondition(!leftovers.contains { $0.bundleID.hasPrefix("systemgroup.") || $0.bundleID == "org.macsweep.shared" })
        print("PASS: System groups and installed vendor shared preferences excluded")
        precondition(leftovers.contains { $0.id == orphan.path })
        print("PASS: Unmatched preference offered only as an uncertain leftover")
        precondition(!leftovers.contains { $0.bundleID.hasPrefix("org.macsweep.fixture") })
        print("PASS: Installed App and helper identifiers excluded from leftovers")
        precondition(!leftovers.contains { $0.bundleID.hasPrefix("com.apple") || $0.bundleID.hasPrefix("com.google.drive") || $0.id.contains("Application Support") })
        print("PASS: System, Drive and dedicated documents excluded from leftover inspector")
        let known = InstalledApp(url: home.appendingPathComponent("External.app"), name: "External", bundleID: "org.retired.example", version: "1", protected: false)
        precondition(!catalog.leftovers(additionalApps: [known]).0.contains { $0.id == orphan.path })
        print("PASS: Manually added installed App suppresses false leftover")
        try fm.removeItem(at: orphan)
        try fm.createSymbolicLink(at: orphan, withDestinationURL: document)
        precondition(!catalog.leftovers().0.contains { $0.id == orphan.path })
        print("PASS: Leftover inspector excludes symlinked preferences")
        let chromeInfo = ["CFBundleIdentifier": "com.google.Chrome", "CFBundleName": "Google Chrome", "CFBundleVersion": "1"]
        _ = try write("Applications/Google Chrome.app/Contents/Info.plist", PropertyListSerialization.data(fromPropertyList: chromeInfo, format: .xml, options: 0))
        let chrome = catalog.readApp(home.appendingPathComponent("Applications/Google Chrome.app"))!
        let chromeProfile = try write("Library/Application Support/Google/Chrome/Default/Bookmarks")
        let chromeCache = try write("Library/Caches/Google/Chrome/Default/data")
        _ = try write("Library/Application Support/Google/DriveFS/offline-document")
        _ = try write("Library/Caches/com.google.Keystone/shared-updater")
        let chromePlan = catalog.plan(chrome, installed: [chrome])
        precondition(chromePlan.files.contains { $0.id == chromeProfile.deletingLastPathComponent().deletingLastPathComponent().path && $0.review })
        precondition(chromePlan.files.contains { $0.id == chromeCache.deletingLastPathComponent().deletingLastPathComponent().path && $0.review })
        print("PASS: Chrome nested profile and cache paths appear without preselection")
        precondition(!chromePlan.files.contains { $0.url.lastPathComponent == "Google" || $0.id.contains("DriveFS") || $0.id.contains("Keystone") })
        print("PASS: Chrome uninstall does not include Google parent, Drive content or shared updater")
        let chromeCopy = InstalledApp(url: home.appendingPathComponent("AnotherChrome.app"), name: chrome.name, bundleID: chrome.bundleID, version: "1", protected: false)
        precondition(catalog.plan(chrome, installed: [chrome, chromeCopy]).files.count == 1)
        print("PASS: Duplicate Chrome installation preserves newly mapped profile paths")
        let drive = InstalledApp(url: app.url, name: "Google Drive", bundleID: "com.google.drivefs", version: "1", protected: false)
        precondition(catalog.relatedPaths(drive).isEmpty)
        precondition(catalog.plan(drive, installed: [drive]).files.allSatisfy { $0.id == drive.id })
        print("PASS: Google Drive associated data never offered for uninstall")
        try fm.removeItem(at: home.appendingPathComponent("Applications/Second.app"))
        let externalURL = home.appendingPathComponent("External/Other.app")
        let externalInfoURL = try write("External/Other.app/Contents/Info.plist", PropertyListSerialization.data(fromPropertyList: info, format: .xml, options: 0))
        let external = catalog.readApp(externalURL)!
        let tracked = catalog.plan(app, installed: [app, external])
        let decoded = try JSONDecoder().decode(UninstallPlan.self, from: JSONEncoder().encode(tracked))
        precondition(decoded.inspectedApps.contains { $0.id == external.id })
        print("PASS: Manually added App locations survive inspection result encoding")
        var externalPlan = plan
        externalPlan.inspectedApps = [app, external]
        let externalDuplicate = catalog.uninstall(externalPlan, selected: Set(plan.files.map(\.id)))
        precondition(externalDuplicate.0.isEmpty && externalDuplicate.1.contains { $0.contains("另一份") })
        print("PASS: Duplicate outside default Applications blocks associated data removal")
        try PropertyListSerialization.data(fromPropertyList: sharedInfo, format: .xml, options: 0).write(to: externalInfoURL)
        let changedExternal = catalog.readApp(externalURL)!
        precondition(changedExternal.bundleID == "net.other.fixture")
        print("PASS: Reading App metadata again observes replaced identity")
        let changedOwner = catalog.uninstall(externalPlan, selected: Set(plan.files.map(\.id)))
        precondition(changedOwner.0.isEmpty && changedOwner.1.contains { $0.contains("已變更或無法讀取") })
        print("PASS: Changed external App identity stops operation before any move")
        externalPlan.inspectedApps = [app, changedExternal]
        let externalShared = catalog.uninstall(externalPlan, selected: Set(plan.files.map(\.id)))
        precondition(externalShared.0.isEmpty && externalShared.1.contains { $0.contains("重疊") })
        print("PASS: Shared owner outside default Applications blocks associated data removal")
        try fm.removeItem(at: externalURL)
        let unavailable = catalog.uninstall(externalPlan, selected: Set(plan.files.map(\.id)))
        precondition(unavailable.0.isEmpty && unavailable.1.contains { $0.contains("已變更或無法讀取") })
        precondition(fm.fileExists(atPath: app.id) && fm.fileExists(atPath: document.path))
        print("PASS: Unavailable recorded App stops cleanup and preserves App and documents")
    }
}
